### ISSUE TITLE
Revisit parameter descriptions

### ISSUE THREAD

**Issue by bits0rcerer** [PeerRequest/api_spec#19]
```yaml
name: review_id
in: path
required: true
description: The id of the review to retrieve
schema:
  type: string
```
`to retrieve` might be misleading because it implies that you always want to retrieve something, which might not always be the case.
